apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80 #port on the service
      nodePort: 30004 # port on the worker node where the app is made accessible
  selector:
    app: myapp
